# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='fav_quotes', to='quotes.User'),
        ),
    ]
